// File generated by flutterfire_cli.
// Never edit this file manually.
// This file is used by the Firebase CLI to configure Firebase services.

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    } else if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    } else if (defaultTargetPlatform == TargetPlatform.windows) {
      return windows;
    } else if (defaultTargetPlatform == TargetPlatform.linux) {
      return linux;
    } else if (defaultTargetPlatform == TargetPlatform.macOS) {
      return macos;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  // ========================
  // ANDROID CONFIGURATION
  // ========================
  // Get these values from your Firebase Console -> Project Settings
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxxxxxxxxxxxxxxxxxxxxxxxxxx', // Replace with your key
    appId: '1:123456789:android:xxxxxxxxxxxxxxxx', // Replace with your app ID
    messagingSenderId: '123456789', // Replace with your sender ID
    projectId: 'zeitnoir-xxxxx', // Replace with your project ID
    databaseURL: 'https://zeitnoir-xxxxx.firebaseio.com',
    storageBucket: 'zeitnoir-xxxxx.appspot.com',
  );

  // ========================
  // iOS CONFIGURATION
  // ========================
  // Get these values from your Firebase Console -> Project Settings
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxxxxxxxxxxxxxxxxxxxxxxxxxx', // Replace with your key
    appId: '1:123456789:ios:xxxxxxxxxxxxxxxx', // Replace with your app ID
    messagingSenderId: '123456789', // Replace with your sender ID
    projectId: 'zeitnoir-xxxxx', // Replace with your project ID
    databaseURL: 'https://zeitnoir-xxxxx.firebaseio.com',
    storageBucket: 'zeitnoir-xxxxx.appspot.com',
    iosBundleId: 'com.example.zeitnoirApp', // Replace with your bundle ID
  );

  // ========================
  // WINDOWS CONFIGURATION
  // ========================
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxxxxxxxxxxxxxxxxxxxxxxxxxx', // Replace with your key
    appId: '1:123456789:windows:xxxxxxxxxxxxxxxx',
    messagingSenderId: '123456789',
    projectId: 'zeitnoir-xxxxx',
    authDomain: 'zeitnoir-xxxxx.firebaseapp.com',
    databaseURL: 'https://zeitnoir-xxxxx.firebaseio.com',
    storageBucket: 'zeitnoir-xxxxx.appspot.com',
  );

  // ========================
  // LINUX CONFIGURATION
  // ========================
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDxxxxxxxxxxxxxxxxxxxxxxxxxx', // Replace with your key
    appId: '1:123456789:linux:xxxxxxxxxxxxxxxx',
    messagingSenderId: '123456789',
    projectId: 'zeitnoir-xxxxx',
    authDomain: 'zeitnoir-xxxxx.firebaseapp.com',
    databaseURL: 'https://zeitnoir-xxxxx.firebaseio.com',
    storageBucket: 'zeitnoir-xxxxx.appspot.com',
  );

  // ========================
  // macOS CONFIGURATION
  // ========================
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxxxxxxxxxxxxxxxxxxxxxxxxxx', // Replace with your key
    appId: '1:123456789:macos:xxxxxxxxxxxxxxxx',
    messagingSenderId: '123456789',
    projectId: 'zeitnoir-xxxxx',
    databaseURL: 'https://zeitnoir-xxxxx.firebaseio.com',
    storageBucket: 'zeitnoir-xxxxx.appspot.com',
    iosBundleId: 'com.example.zeitnoirApp', // Replace with your bundle ID
  );
}
