# Define iOS platform
platform :ios, '12.0'

# Disable CocoaPods analytics
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  # Flutter Pod helper
  flutter_application_path = '../'
  load File.join(flutter_application_path, '.flutter-plugins-dependencies')

  # Firebase pods
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

end

# Post-install tweaks for Flutter & Firebase
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
