platform :ios, '12.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

use_frameworks! :linkage => :static
use_modular_headers!

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
